name: Deploy the backend
on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.backend
                push: true
                tags: fardeen26/docker-deploy-monorepo:${{ github.sha }}

            # - name: Deploy to VM
            #   run: |
            #     echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
            #     chmod 700 /home/runner/ssh_key
            #     ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@15.207.115.242 -t "docker stop deploy_monorepo_be && docker run --name deploy_monorepo_be -d -p 8080:8080 fardeen26/docker-deploy-monorepo:${{ github.sha }}"

            - name: Deploy to VM
              run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/ssh_key
                chmod 600 /home/runner/ssh_key
                ssh -o StrictHostKeyChecking=no -i /home/runner/ssh_key ubuntu@15.207.115.242 -t \
                  "docker stop deploy_monorepo_be || true && docker rm deploy_monorepo_be || true && docker run --name deploy_monorepo_be -d -p 8080:8080 fardeen26/docker-deploy-monorepo:${{ github.sha }}"
